import { useEffect, useRef, useState } from "react";
import { faqs, siteConfig, testimonials, type Testimonial } from "../data/bodyReset";

declare global { interface Window { dataLayer?: Record<string, unknown>[]; fbq?: (...args: unknown[]) => void } }
const track=(event:string,detail:Record<string,unknown>={})=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...detail})};
function checkout(){if(!siteConfig.checkoutUrl)return "#offer";const u=new URL(siteConfig.checkoutUrl,location.href);["utm_source","utm_medium","utm_campaign","utm_content","utm_term"].forEach(k=>{const v=new URLSearchParams(location.search).get(k)||sessionStorage.getItem(k);if(v)u.searchParams.set(k,v)});return u.toString()}
function CTA({children,event="offer_cta_click",small=false}:{children:React.ReactNode;event?:string;small?:boolean}){return <a className={`cta ${small?"cta-small":""}`} href={checkout()} onClick={()=>{track(event);track("checkout_click",{placement:event});if(siteConfig.checkoutUrl&&siteConfig.metaPixelId&&window.fbq)window.fbq("track","InitiateCheckout")}}>{children}</a>}
function Placeholder({children,tall=false}:{children:React.ReactNode;tall?:boolean}){return <div className={`asset ${tall?"asset-tall":""}`}><span>{children}</span><small>APPROVED MEDIA TO BE ADDED</small></div>}
function Proof({id,compact=false}:{id:number;compact?:boolean}){const item=testimonials[id-1];return <button className={`proof ${compact?"proof-compact":""}`} onClick={()=>{if(item.type==="video")track("testimonial_video_play",{id:item.id,placeholder:true});window.dispatchEvent(new CustomEvent("open-proof",{detail:item}))}}><span>TESTIMONIAL {String(id).padStart(2,"0")}</span><strong>{item.type.replace("beforeAfter","BEFORE / AFTER").toUpperCase()}</strong><small>MEDIA TO BE ADDED · TAP TO ENLARGE</small></button>}
function ProofLightbox(){const [item,setItem]=useState<Testimonial|null>(null);useEffect(()=>{const open=(e:Event)=>{setItem((e as CustomEvent<Testimonial>).detail);track("testimonial_lightbox_open")};addEventListener("open-proof",open);return()=>removeEventListener("open-proof",open)},[]);useEffect(()=>{if(!item)return;document.body.classList.add("overlay-open");const key=(e:KeyboardEvent)=>e.key==="Escape"&&setItem(null);addEventListener("keydown",key);return()=>{document.body.classList.remove("overlay-open");removeEventListener("keydown",key)}},[item]);if(!item)return null;return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setItem(null)}><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="proof-title"><button autoFocus className="close" onClick={()=>setItem(null)} aria-label="Close">×</button><h2 id="proof-title">TESTIMONIAL {item.id.slice(-2)}</h2><Placeholder tall>{item.type.toUpperCase()} TESTIMONIAL PLACEHOLDER</Placeholder><p className="fine">No testimonial copy has been invented. Replace this with permissioned customer media.</p></div></div>}
function PurchaseNotification(){const records=siteConfig.purchaseNotifications.records;const [visible,setVisible]=useState(false);useEffect(()=>{if(!siteConfig.purchaseNotifications.enabled||!records.length)return;const show=setTimeout(()=>setVisible(true),12000);const hide=setTimeout(()=>setVisible(false),17000);return()=>{clearTimeout(show);clearTimeout(hide)}},[records.length]);if(!siteConfig.purchaseNotifications.enabled||!records.length||!visible)return null;const record=records[0];return <aside className="sales-toast" aria-live="polite"><b aria-hidden="true">✓</b><span>{record.firstName||"Someone"}{record.city?` in ${record.city}`:""} recently joined Body Reset.</span></aside>}
const Lines=({children}:{children:string})=><div className="lines">{children.split("\n").filter(Boolean).map((x,i)=><p key={i}>{x}</p>)}</div>;
const Section=({children,tone="ivory",id,className=""}:{children:React.ReactNode;tone?:string;id?:string;className?:string})=><section id={id} className={`section ${tone} ${className}`}><div className="copy">{children}</div></section>;
function FAQ(){const [open,setOpen]=useState<number|null>(null);return <Section tone="tint"><p className="kicker">CLEAR ANSWERS</p><h2>AND BEFORE YOU ASK…</h2><div className="faq">{faqs.map(([q,a],i)=><div className="faq-row" key={q}><h3><button aria-expanded={open===i} aria-controls={`faq-${i}`} onClick={()=>{setOpen(open===i?null:i);track("faq_open",{question:q})}}><span>{q}</span><b>{open===i?"−":"+"}</b></button></h3>{open===i&&<div id={`faq-${i}`} className="faq-answer">{a.split("\n").map((p,j)=><p key={j}>{p}</p>)}</div>}</div>)}</div></Section>}
const offerItems=[
["COMPLETE BODY RESET CLASS","Full step-by-step training through video, audio, text and practical screen recordings."],["NIGERIAN FOOD & CALORIE GUIDE","A practical guide to foods you recognize and homemade recipes that vary."],["PERSONAL STARTING-POINT CALCULATOR","Work out a sensible starting estimate based on your own information."],["FOOD-WEIGHING MASTERCLASS","Raw vs cooked measurements, oil, rice, yam, soups, stew and mixed meals."],["BUILD-YOUR-OWN MEAL SYSTEM","Put meals together around your goal instead of depending on a rigid menu."],["HERBAL RECIPE VAULT","Victoria's supporting homemade recipes, instructions and realistic expectations."],["REAL-LIFE WEIGHT-LOSS GUIDE","Owambe, restaurants, weekends, travel, cravings and imperfect days."],["PLATEAU & PROGRESS GUIDE","Know what to check when the scale isn't moving."],["BODY RESET TRACKERS & CHECKLISTS","Track progress, measurements, habits and what actually matters."],["MAINTENANCE BLUEPRINT","Learn what happens after weight loss so old patterns don't simply return."],["ACTIVE PRIVATE BODY RESET COMMUNITY","Ask questions, share wins and get ongoing support while using the program."]];
export default function BodyResetPage(){const heroRef=useRef<HTMLDivElement>(null);const finalRef=useRef<HTMLElement>(null);const [sticky,setSticky]=useState(false);const [exit,setExit]=useState(false);const [more,setMore]=useState(false);
useEffect(()=>{document.title="The Body Reset — Lose Weight Without Giving Up Nigerian Food";track("page_view");if(siteConfig.metaPixelId&&window.fbq)window.fbq("track","ViewContent",{content_name:siteConfig.productName,value:siteConfig.price,currency:siteConfig.currency});const p=new URLSearchParams(location.search);["utm_source","utm_medium","utm_campaign","utm_content","utm_term"].forEach(k=>{const v=p.get(k);if(v)sessionStorage.setItem(k,v)});const obs=new IntersectionObserver(es=>{const heroVisible=es.find(x=>x.target===heroRef.current)?.isIntersecting??false;const finalVisible=es.find(x=>x.target===finalRef.current)?.isIntersecting??false;setSticky(!heroVisible&&!finalVisible)});if(heroRef.current)obs.observe(heroRef.current);if(finalRef.current)obs.observe(finalRef.current);const fired=new Set<number>();const scroll=()=>{const n=(scrollY+innerHeight)/document.documentElement.scrollHeight*100;[25,50,75,90].forEach(x=>{if(n>=x&&!fired.has(x)){fired.add(x);track(`scroll_${x}`)}})};const leave=(e:MouseEvent)=>{if(e.clientY<=4&&scrollY>innerHeight&&!sessionStorage.getItem("exit_seen")){sessionStorage.setItem("exit_seen","1");setExit(true)}};addEventListener("scroll",scroll,{passive:true});document.addEventListener("mouseout",leave);return()=>{obs.disconnect();removeEventListener("scroll",scroll);document.removeEventListener("mouseout",leave)}},[]);
return <main>
<header className="sales-header"><div className="wide header-inner"><a className="wordmark" href="#top">THE BODY <i>RESET</i></a><CTA small event="header_cta_click">START NOW</CTA></div></header>
<section className="hero" id="top"><div className="wide hero-grid"><div><p className="hero-kicker">FOR NIGERIAN WOMEN WHO WANT TO LOSE WEIGHT WITHOUT MAKING THEIR WHOLE LIFE ABOUT DIETING</p><h1>WHAT IF YOU COULD <em>LOSE THE WEIGHT…</em><br/>WITHOUT GIVING UP RICE, SWALLOW, BREAD OR THE FOOD YOU ACTUALLY LOVE?</h1><div className="hero-lines"><p>No starving yourself.</p><p>No surviving on salad and boiled eggs.</p><p>No starting another diet you'll abandon in three weeks.</p></div><p className="hero-support">The Body Reset shows you how to make weight loss work with the Nigerian food and real life you already have.</p><div ref={heroRef}><CTA event="hero_cta_click">START MY BODY RESET — ₦14,900</CTA><p className="micro">Beginner friendly • Nigerian-food friendly • Instant access</p></div></div><div className="hero-media"><Placeholder tall>VICTORIA + BODY RESET PRODUCT MOCKUP</Placeholder><div className="hero-proof"><Proof id={1} compact/></div></div></div></section>

<Section><p className="kicker">BE HONEST…</p><h2>AREN'T YOU TIRED OF STARTING OVER?</h2><p>You know the routine. Monday comes and suddenly you're serious.</p><div className="chips"><b>NO RICE.</b><b>NO BREAD.</b><b>NO EATING AFTER 6PM.</b></div><Lines>{`You're drinking water like your life depends on it. 😭\nMaybe you're fasting. Maybe you're drinking one tea morning and night.\nMaybe you downloaded another meal plan. Maybe you finally started using that gym membership.\nAnd for a few days? You're doing WELL.`}</Lines><div className="turn"><strong>THEN LIFE HAPPENS.</strong><span>An outing. A stressful week. An owambe. A craving. One meal you didn't plan for.</span></div><p>And suddenly: <mark>“I've spoiled it. I'll start again on Monday.”</mark></p><p>Then Monday comes again. And somehow you've been “starting again” for months.</p></Section>

<Section tone="tint"><p className="kicker">THE FRUSTRATING PART</p><h2>AND THE ANNOYING PART?</h2><h3>IT'S NOT LIKE YOU HAVEN'T BEEN TRYING.</h3><Lines>{`You've tried eating less. Cutting certain foods. Fasting. Teas. Videos. Meal plans.\nYou've told yourself: “This time, I'm really going to lose this weight.”\nAnd maybe you've even lost weight before. But sooner or later… you're back wondering what to try next.`}</Lines><div className="mirror">You're still checking your stomach first when somebody sends you a picture.<br/><strong>“I just want to lose this weight and feel like myself again.”</strong></div><Proof id={2}/></Section>

<Section tone="light" className="belief"><p className="kicker">A DIFFERENT POSSIBILITY</p><h2>MAYBE YOU DON'T NEED TO TRY HARDER.</h2><h3>MAYBE YOU NEED TO STOP DOING WEIGHT LOSS BY TRIAL AND ERROR.</h3><div className="rule-rain">{["STOP CARBS","NEVER TOUCH BREAD","EAT ONCE A DAY","SIX SMALL MEALS","DON'T EAT AFTER 6","WALK 10,000 STEPS","REMOVE SWALLOW"].map(x=><span key={x}>{x}</span>)}</div><p className="shout">“ABEG, WHAT AM I ACTUALLY SUPPOSED TO EAT?” 😭</p><p>Most women are not stuck because they don't want the result badly enough. They're collecting rules without ever understanding how the whole thing works.</p></Section>

<Section className="rice"><p className="kicker">HERE'S THE GOOD NEWS…</p><h2>YOU WERE NEVER SUPPOSED TO BE AFRAID OF RICE.</h2><Lines>{`Rice isn't automatically the problem. Neither is yam. Bread isn't automatically the problem. Beans aren't automatically the problem.\nAnd yes… even swallow can still exist in your life.`}</Lines><div className="versus"><div><small>THE OLD QUESTION</small><strong>“Can I eat this?”</strong></div><i>VS</i><div><small>THE BETTER QUESTION</small><strong>“How much works with my goal?”</strong></div></div><p>The amount matters. How it was prepared matters. The oil matters. What you ate with it matters. What the rest of your day looked like matters.</p><p className="big-line">Once somebody explains those things properly, food becomes much less confusing. <em>That changes everything.</em></p></Section>

<Section tone="tint"><p className="kicker">THE MEAL-PLAN TRAP</p><h2>BECAUSE YOU DON'T NEED ANOTHER MEAL PLAN TO FOLLOW BLINDLY.</h2><div className="menu-note"><span>MON — OATS</span><span>TUE — EGGS</span><span>WED — SALAD</span><span>THU — CHICKEN</span></div><p>Fine. But what happens when your family makes jollof? When you're at a wedding? Travelling? When you don't have the exact food? What happens on Day 31?</p><p>If nobody taught you <strong>why</strong> the meal plan worked, you'll always need another person to tell you what to eat.</p><h3>AND THAT'S EXACTLY WHAT I DON'T WANT FOR YOU.<br/><em>I want you to know what you're doing.</em></h3><Proof id={3} compact/></Section>

<Section className="story"><p className="kicker">VICTORIA'S STORY</p><h2>I HAD TO LEARN THIS FOR MYSELF FIRST.</h2><div className="split"><Placeholder tall>VICTORIA PORTRAIT / PERSONAL TRANSFORMATION</Placeholder><div><p>Hi, I'm Victoria.</p><p>I didn't create Body Reset because I woke up one morning and thought, “Let me make another weight-loss ebook.” I created it because I've had my own journey too.</p><p>At one point, I weighed around 94kg. I wanted the weight gone, but I didn't want my entire life to become one long punishment because I wanted to be smaller.</p><p>So I learned about portions, paid attention to how much I was eating, changed parts of my routine and incorporated homemade herbal recipes into my own lifestyle.</p><p>Over the course of my own journey, my weight moved from around <strong>94kg to 80kg.</strong></p></div></div><Placeholder>VICTORIA TRANSFORMATION PHOTO</Placeholder><div className="weight-shift" aria-label="Victoria’s personal weight change"><strong>94<small>KG</small></strong><span>↓</span><strong>80<small>KG</small></strong></div><p className="disclaimer">That's my personal experience, not a promise that everybody will lose the same amount or lose weight at the same speed. Every person's starting point and circumstances are different.</p><p className="big-line">Weight loss stopped feeling mysterious. Women weren't necessarily lazy or unserious. <em>A lot of them simply did not understand what they were doing.</em></p></Section>

<section className="section proof-section"><div className="wide"><div className="copy"><p className="kicker">EARLY PROOF</p><h2>AND THEN I STARTED SEEING WOMEN MAKE THEIR OWN PROGRESS TOO.</h2><p>Different women. Different bodies. Different starting points. When women understand what they're doing, everything starts making more sense.</p></div><div className="proof-grid">{[4,5,6,7].map(n=><Proof key={n} id={n}/>)}</div><p className="disclaimer center">Individual experiences vary. Results depend on starting point, consistency, lifestyle and individual circumstances.</p></div></section>

<section className="product-reveal" id="product"><div className="wide product-grid"><div><p className="kicker">SO I PUT EVERYTHING INTO ONE SIMPLE SYSTEM.</p><h2>MEET THE<br/><em>BODY RESET.</em></h2><p>A practical weight-loss program that teaches you how to lose weight with food you actually eat — instead of depending on another restrictive diet you can't wait to escape from.</p><Lines>{`No complicated nutrition grammar.\nNo pretending you suddenly want dry salad every night.\nNo telling you rice is forbidden for the rest of your natural life. 😭`}</Lines><CTA event="product_reveal_cta">GET THE BODY RESET — ₦14,900</CTA></div><Placeholder tall>BODY RESET PRODUCT MOCKUP · PHONE + TABLET</Placeholder></div></section>

<Section><p className="kicker">A REAL PROGRAM — NOT A PDF DUMP</p><h2>THIS ISN'T JUST AN EBOOK YOU'LL DOWNLOAD AND FORGET.</h2><p className="lead">Body Reset is a full step-by-step digital class designed to teach you properly.</p><div className="formats">{[["▶","VIDEO LESSONS","Short, simple classes."],["▣","SCREEN RECORDINGS","See calculations and food tracking demonstrated."],["♪","AUDIO LESSONS","Listen while cooking or commuting."],["≡","TEXT & QUICK GUIDES","Return whenever you need a refresher."],["↓","DOWNLOADABLE TOOLS","Guides, calculators, trackers and checklists."],["♥","ACTIVE PRIVATE COMMUNITY","Ask questions, share progress and get support."]].map(([i,t,d])=><article key={t}><b>{i}</b><h3>{t}</h3><p>{d}</p></article>)}</div></Section>

<Section tone="tint"><p className="kicker">STEP BY STEP</p><h2>HERE'S WHAT WE'RE GOING TO DO.</h2><div className="steps">{[["01","FIRST — FIGURE OUT WHERE YOU'RE STARTING FROM.","Find a sensible starting point based on you—not somebody else."],["02","THEN — MAKE YOUR FOOD MAKE SENSE.","Rice, yam, raw or cooked, oil, stew, whole pots and foods missing from your app. I'll show you."],["03","THEN — BUILD YOUR OWN MEALS.","So you're not messaging somebody every Tuesday asking: ‘Ma, can I eat bread?’ 😭"],["04","THEN — DO IT IN REAL LIFE.","Owambe, restaurants, periods, travel, cravings, busy days, imperfect meals and stubborn scales."]].map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div><CTA event="process_cta_click">I'M READY TO START — ₦14,900</CTA></Section>

<Section><p className="kicker">THE SHIFT</p><h2>THIS IS THE REAL RESET.</h2><div className="contrast">{[["Can I eat rice?","I understand my portion."],["How many calories is this?","I know how to work it out."],["I've spoiled everything. I'll start Monday.","One meal doesn't cancel my progress."],["Just send me a meal plan.","I know how to build my own meals."],["Another diet. Another restart.","I understand how to manage my food."]].map(([a,b])=><div key={a}><span><small>BEFORE</small>{a}</span><b>→</b><span><small>AFTER</small>{b}</span></div>)}</div></Section>

<Section tone="dark"><p className="kicker">PICTURE THIS</p><h2>AND JUST IMAGINE WHAT THAT COULD MEAN FOR YOU.</h2><Lines>{`Eating rice without guilt simply because rice touched your plate.\nKnowing what you're doing when you cook.\nGoing to an owambe without thinking you've destroyed your week.\nSeeing your clothes gradually begin to sit differently. Feeling lighter.\nGetting dressed and actually enjoying what you're wearing.\nNot searching every few weeks for the next thing that'll finally make you lose weight.`}</Lines><p className="shout">BECAUSE NOW? YOU HAVE A SYSTEM.</p><Proof id={8}/></Section>

<section className="section offer-bg" id="offer"><div className="offer-card"><span className="badge">FULL DIGITAL CLASS + TOOLS + PRIVATE COMMUNITY</span><h2>EVERYTHING YOU GET INSIDE<br/><em>THE BODY RESET</em></h2><div className="offer-list">{offerItems.map(([t,d],i)=><article key={t}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</div><div className="summary"><h3>YOU GET:</h3><div>{["Full multi-format Body Reset class","Video lessons","Audio lessons","Screen recordings","Text lessons","Nigerian food guide","Calculators","Trackers & checklists","Herbal recipe vault","Real-life guides","Active private community"].map(x=><span key={x}>✓ {x}</span>)}</div></div><p className="access">COMPLETE ACCESS TODAY</p><div className="price">₦14,900</div><CTA>YES — I WANT THE BODY RESET</CTA><p className="micro">Secure payment • Instant access after payment • Beginner friendly</p>{!siteConfig.checkoutUrl&&<p className="setup">Checkout is intentionally inactive until <code>checkoutUrl</code> is configured.</p>}<Countdown/></div></section>

<section className="section proof-wall"><div className="wide"><div className="copy"><p className="kicker">PROOF, NOT PROMISES</p><h2>REAL WOMEN. REAL EXPERIENCES.</h2><p>You don't have to take my word for it. This space is ready for the messages, pictures and updates received from women Victoria has worked with.</p></div><h3 className="break">SOMETIMES THE FIRST CHANGE THEY NOTICE IS ON THE SCALE.</h3><div className="proof-grid">{[9,10,13].map(n=><Proof key={n} id={n}/>)}</div><h3 className="break">SOMETIMES IT'S HOW THEIR STOMACH OR CLOTHES LOOK.</h3><div className="proof-grid">{[11,14].map(n=><Proof key={n} id={n}/>)}</div>{more&&<><h3 className="break">AND SOMETIMES THE WINS AREN'T SOMETHING A SCALE CAN MEASURE.</h3><div className="proof-grid"><Proof id={12}/><Proof id={15}/></div></>}{!more&&<button className="outline-btn" onClick={()=>setMore(true)}>SEE MORE RESULTS</button>}<p className="disclaimer center">Individual experiences vary. Results depend on factors including starting point, consistency, lifestyle and individual circumstances.</p></div></section>

<FAQ/>
<Section><p className="kicker">FROM VICTORIA</p><h2>ONE MORE THING…</h2><div className="letter"><p>I don't want you to depend on me forever. Seriously.</p><p>I don't want you messaging somebody for the next five years every time you want to eat yam: “Ma, can I eat this?” 😭</p><p>I want you to understand your food. Your portions. Your progress. What to do when things don't go perfectly.</p><strong>YOU KNOW WHAT YOU'RE DOING.</strong><p>That is what I built Body Reset to teach you.</p><i>— Victoria</i></div></Section>

<section className="section decision"><div className="wide"><div className="copy"><p className="kicker">THE DECISION</p><h2>RIGHT NOW, YOU REALLY HAVE TWO OPTIONS.</h2></div><div className="paths"><article><span>OPTION 1</span><h3>CLOSE THIS PAGE.</h3><p>And nothing changes. Back to wondering whether to stop rice, fast again or avoid food after 6pm. Back to saving another meal plan and starting every Monday determined.</p><p>Another tea. Another diet. Another challenge. Still wanting to lose the weight. Still asking: <strong>“What exactly am I supposed to be doing?”</strong></p></article><b className="or">OR</b><article><span>OPTION 2</span><h3>STOP GUESSING AND FINALLY LEARN HOW TO DO THIS PROPERLY.</h3><p>Learn what your body roughly needs. Learn your portions. Learn how rice, yam, bread, beans and swallow can fit. Build your own meals. Handle owambe, imperfect days and a scale that refuses to cooperate.</p><p>Stop asking “Can I eat this?” because <strong>YOU ACTUALLY KNOW WHAT YOU'RE DOING.</strong></p></article></div><p className="decision-close">There is no perfect Monday coming. There is just the decision to stop repeating the same cycle—and learn a way you can actually live with.</p></div></section>

<section className="final" ref={finalRef}><div className="copy center"><p className="kicker">YOUR NEXT STEP</p><h2>THE BODY RESET</h2><p>Full digital class + practical tools + active private community</p><div className="price">₦14,900</div><CTA event="final_cta_click">YES — I'M READY TO START MY BODY RESET</CTA><p className="micro">Secure payment • Instant access • Beginner friendly</p><Proof id={15}/><p className="closing">You already know what starting over feels like.<br/><em>Maybe this time, learn how to stop needing to.</em></p></div></section>

<footer><div className="wide"><a className="wordmark" href="#top">THE BODY <i>RESET</i></a><nav aria-label="Legal"><a href="#">Privacy Policy [TODO]</a><a href="#">Terms [TODO]</a><a href="#">Refund Policy [TODO]</a><a href="#">Contact / Support [TODO]</a></nav><p>The Body Reset provides general educational information about nutrition, lifestyle and weight management. It is not medical advice and is not intended to diagnose, treat, cure or prevent any medical condition. Individual circumstances differ. Consult an appropriate healthcare professional where necessary.</p><small>© {new Date().getFullYear()} The Body Reset. All rights reserved.</small></div></footer>
<div className={`sticky ${sticky?"show":""}`}><div><strong>BODY RESET</strong><span>₦14,900</span></div><CTA small event="sticky_cta_click">START NOW</CTA></div>
<ProofLightbox/><PurchaseNotification/>{exit&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setExit(false)}><div className="dialog exit" role="dialog" aria-modal="true" aria-labelledby="exit-title"><button autoFocus className="close" onClick={()=>setExit(false)} aria-label="Close">×</button><p className="kicker">BEFORE YOU GO…</p><h2 id="exit-title">Still wondering whether Body Reset is right for you?</h2><p>✓ Full step-by-step class<br/>✓ Built around familiar Nigerian food<br/>✓ Beginner friendly<br/>✓ Private community included</p><a className="cta" href="#offer" onClick={()=>setExit(false)}>SEE EVERYTHING I'M GETTING</a><button className="text-btn" onClick={()=>setExit(false)}>CONTINUE READING</button></div></div>}
</main>}
function Countdown(){const c=siteConfig.countdown;const [left,setLeft]=useState(0);useEffect(()=>{if(!c.enabled||!c.deadline)return;const tick=()=>setLeft(Math.max(0,new Date(c.deadline).getTime()-Date.now()));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[c.enabled,c.deadline]);if(!c.enabled||!c.deadline||left<=0)return null;const s=Math.floor(left/1000);const parts=[[Math.floor(s/86400),"DAYS"],[Math.floor(s%86400/3600),"HOURS"],[Math.floor(s%3600/60),"MIN"],[s%60,"SEC"]];return <div className="countdown"><strong>{c.headline}</strong><div>{parts.map(([n,l])=><span key={l}><b>{String(n).padStart(2,"0")}</b><small>{l}</small></span>)}</div></div>}
